COMMON: &common #标识
  DEBUG: False
  SECRET_KEY: "fHoNCXiQeSCqGcZ*"

  # 页码设置
  DEFAULT_PAGE_INDEX: 1
  DEFAULT_PAGE_SIZE: 10

  # 文件配置
  UPLOAD_FOLDER: './sources/'

  # 业务数据库连接
  SQLALCHEMY_DATABASE_URI: 'sqlite:///info.db'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  SQLALCHEMY_ECHO: False
  SQLALCHEMY_POOL_RECYCLE: 8
  # 日志配置文件路径
  LOGGING_CONFIG_PATH: ./config/logging.yaml
  # 日志文件存放位置
  LOGGING_PATH: ./logs

  # 响应消息
  RESPONSE_MESSAGE: ./config/msg.yaml

  # 是否开启定时任务,默认不开启
  SCHEDULER_OPEN: True

  # 定时任务配置
  SCHEDULER_API_ENABLED: True
  SCHEDULER_TIMEZONE: 'Asia/Shanghai'


DEVELOPMENT: &development
  <<: *common # 继承common，没有重新定义的变量，使用common变量值
  DEBUG: True
  SQLALCHEMY_ECHO: False

STAGING: &staging
  <<: *common
  SECRET_KEY: sortasecure

PRODUCTION: &production
  <<: *common
  SECRET_KEY: mdd1##$$%^!DSA#FDSF
  SQLALCHEMY_ECHO: False
