# 知识库初始化配置文件, 用于初始化知识库和Embedding模型, 该文件只在初始化时使用。 后续修改可直接在数据库中修改。

# LLM模型配置
LLM_MODELS:
  - name: "DeepSeek-R1-Distill-Qwen-1.5B"
    deployment_type: "local"  # cloud 或 local
    category: "llm"
    api_base: ""
    api_key: ""  # Please replace with your actual API key
    path: "./backend/local_models/DeepSeek-R1-Distill-Qwen-1.5B"  # Local model path
    description: "DeepSeek-R1-Distill-Qwen-1.5B LLM model"
    temperature: 0.3
    max_tokens: 260000


# Embedding model configuration
EMBEDDING_MODELS:
  # OpenAI Embedding model
  - name: "all-MiniLM-L6-v2"
    deployment_type: "local"  # cloud 或 local
    category: "embedding"
    api_base: ""
    api_key: ""  # Please replace with your actual API key
    path: "./backend/local_models/all-MiniLM-L6-v2"  # Local model path
    dimension: 384
    description: "Embedding model, used to generate text vectors"

# Knowledge base configuration
KNOWLEDGE_BASES:
  # MySQL knowledge base
  - kb_name: "mysql_knowledge"
    db_type: "mysql"
    kb_info: "MySQL knowledge base, contains MySQL keywords, functions, operators, etc."
    embedding_model: "all-MiniLM-L6-v2"  # Use the Embedding model defined above
    knowledge_files:
      - "./data/processed_document/mysql_8_kb.json"

  # PostgreSQL knowledge base
  - kb_name: "postgresql_knowledge"
    db_type: "postgresql"
    kb_info: "PostgreSQL knowledge base, contains PostgreSQL keywords, functions, operators, etc."
    embedding_model: "all-MiniLM-L6-v2"
    knowledge_files:
      - "./data/processed_document/pg_14_kb.json"

  # Oracle knowledge base
  - kb_name: "oracle_knowledge"
    db_type: "oracle"
    kb_info: "Oracle knowledge base, contains Oracle keywords, functions, operators, etc."
    embedding_model: "all-MiniLM-L6-v2"
    knowledge_files:
      - "./data/processed_document/oracle_11_kb.json" 