// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomInputContainer: typeof import('./../src/components/BottomInputContainer.vue')['default']
    ChatItem: typeof import('./../src/components/ChatItem.vue')['default']
    Code_demo: typeof import('./../src/components/code_demo.vue')['default']
    CreateKnowledgeBase: typeof import('./../src/components/CreateKnowledgeBase.vue')['default']
    DatabaseConfigForm: typeof import('./../src/components/DatabaseConfigForm.vue')['default']
    ElSvgIcon: typeof import('./../src/components/ElSvgIcon.vue')['default']
    ProcessItem: typeof import('./../src/components/ProcessItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SqlInput: typeof import('./../src/components/SqlInput.vue')['default']
    SvgIcon: typeof import('./../src/icons/SvgIcon.vue')['default']
  }
}
